import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Login from "./LoginBtn";
import "./globals.css";
import { getServerSession } from "next-auth";
import LogOut from "./LogoutBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let a = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        {a ? <LogOut /> : <Login />}
        {a ? a.user.name + "님 안녕하세여" : null}
        {children}
      </body>
    </html>
  );
}
